import { Inter } from 'next/font/google';
import type { Metadata } from "next";
import "../styles/globals.css";
import { Header } from '@/components/layouts/Header';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Пошук роботи",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}

