import { Inter } from 'next/font/google';
import type { Metadata } from "next";
import "../styles/globals.css";
import { Header } from '@/components/layouts/Header';
import { Footer } from '@/components/layouts/Footer';
import { AuthProvider } from '@/components/hook/isLoggedIn';
import ToastProvider from '@/components/ui/toastProvider';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Joobly.ua",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <AuthProvider> 
      <html lang="en">
        <head>
          <link rel="icon" href="/images/favicon/favicon.png" />
        </head>
        <body className={inter.variable}>
          <Header />
            <ToastProvider>
            {children}
          </ToastProvider>
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}

